color: null
description: null
fieldLayouts:
  0af731bc-b8d2-4eee-861d-b2c946866665:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-03T13:05:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3e18e51e-c692-4a4c-86b7-8cb0277cfed7 # Text
            handle: firstName
            includeInCards: false
            instructions: null
            label: 'First Name'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 838fd9ba-7e1f-43b8-b83c-f71b8733e8c3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-03T13:05:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3e18e51e-c692-4a4c-86b7-8cb0277cfed7 # Text
            handle: lastName
            includeInCards: false
            instructions: null
            label: 'Last Name'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2a15308-e693-4957-8a0d-cb84dbfcfcf4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-03T13:05:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d60bf066-159d-4fbe-8469-d16431848e03 # Email
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e425286-3eef-493c-93ab-d8229cfb973a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 70e50428-723a-4204-a513-2028d43d7f1f
        userCondition: null
handle: subscriber
hasTitleField: false
icon: person
name: Subscriber
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{email}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
