fieldLayouts:
  2d5d24a7-5ea5-4fbb-a4b6-84969b3155ff:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-07T21:27:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3e18e51e-c692-4a4c-86b7-8cb0277cfed7 # Text
            handle: siteName
            includeInCards: false
            instructions: null
            label: 'Site Name'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc93ca33-e369-44bd-a39b-a7c7467197d7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-07T21:29:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 614a0f80-17f1-41dd-bb25-adee56cc18e4 # Summary
            handle: metaDescription
            includeInCards: false
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73d6c4d7-ae9f-4fdf-957a-e7e562d5f21b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-07T21:29:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 41218836-6831-49f3-9a90-01aff59d5439 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76f37823-65cb-4b24-96ef-f76b766278ac
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6142b658-dca7-4d30-8588-402084a6fe36
        userCondition: null
handle: seo
name: SEO
sortOrder: 5
